### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by chrisveness** [rkusa/co-bcryptjs#1]
Sorry if this is a noob question, but I don't follow how to use co-bcryptjs with koa-passport.

I was expecting to do something along the lines of...

``` js
var passport      = require('koa-passport');
var LocalStrategy = require('passport-local').Strategy;
var bcrypt        = require('co-bcryptjs');

passport.use(new LocalStrategy(function(username, password, done) {
    // retrieve user...

    if (!user) done(null, false); // user not found

    var match = yield bcrypt.compare(password, user.password);
    if (!match) done(null, false); // password match failed

    // validated ok, return user details
    done(null, user);
}));
```

... but I can't make sense of what I should be doing with the yields, *'s, and callbacks.

Can you help? Thx.

**Comment by rkusa** [comment]
Every `yield` call must be inside a generator function. Usage example:

``` js
var co = require('co')
passport.use(new LocalStrategy(opts, function(email, password, done) {
  co(function*() {
    var user = yield User.byEmail(email)

    if (!user) return false

    if (!(yield bcrypt.compare(password, user.password))) {
      return false
    }

    return user
  }).then(function(res) { done(null, res) }, done)
}))
```

**Comment by chrisveness** [comment]
Fantastic! That works a treat. I'll be glad when I can just _yield_ and not have to wrap my head around promises and callbacks...

Also... can you point me to a reference (or offer an example) for how to use koa-passport DigestStrategy with bcrypt-hashed passwords? – the only examples I can find are with plain-text passwords. Or should I address that to @jaredhanson?

Many thanks.

**Comment by rkusa** [comment]
I don't have an example of using DigestStrategy with koa-passport. Does wrapping the callback with `co` not work?

**Comment by chrisveness** [comment]
Scratch that, I think I was getting ahead of myself there. I don't want the cost of doing a bcrypt.compare for every API call! (which is where I was heading). So I think I will structure things differently so that there is an _/auth_ resource (or something) which does the bcrypt.compare and returns the hash, which will then be used in subsequent requests (slightly equivalent to a login, but without sessions). I think that ends up just as secure. If the digest auth uses the hash rather than the clear password, I hope I will be able to use Jared's examples.

Thanks for your help. I'll let you have an example usage when I've got it all sorted!

**Comment by chrisveness** [comment]
A bit more browsing, and I've decided to forget digest auth: see [stackoverflow #18551954](http://stackoverflow.com/questions/18551954#answer-18828089) for good summary. I'll stick with local strategy / standard providers for web, & basic auth + SSL for API. 

Your example works perfectly, but I do look forward to _yield_ing to a LocalStrategy without having to use _co_!
